name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Selecciona la acción de Terraform que deseas ejecutar'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      # Este paso siempre te mostrará qué va a pasar según tu elección
      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform plan -destroy
          else
            terraform plan
          fi

      # Se ejecuta SOLO si elegiste 'apply' en el menú
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      # Se ejecuta SOLO si elegiste 'destroy' en el menú
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve


